document.write(
  `
  <p style="text-align: right;">
    <img src="./img_flower.png" style="width: 50%;opacity: 0.3;">
  </p>
  <h3>브라우저에 사용 가능한 색상이름</h3>
  <div>
    <div style=" display: inline-block; background-color: Red;width: 24%;text-align: center;">Red</div>
    <div style=" display: inline-block; background-color: Yellow;width: 24%;text-align: center;">Yellow</div>
    <div style=" display: inline-block; background-color: Green;width: 24%;text-align: center;">Green</div>
    <div style=" display: inline-block; background-color: Blue;width: 24%; color: yellow; text-align: center;">Blue</div>
    <div style=" display: inline-block; background-color: DarkRed;width: 24%;text-align: center;">DarkRed</div>
    <div style=" display: inline-block; background-color: Gold;width: 24%;text-align: center;">Gold</div>
    <div style=" display: inline-block; background-color: DarkGreen;width: 24%;text-align: center;">DarkGreen</div>
    <div style=" display: inline-block; background-color: DarkBlue;width: 24%; color: yellow;text-align: center;">DarkBlue</div>
    <div style=" display: inline-block; background-color: Maroon;width: 24%;text-align: center;">Maroon</div>
    <div style=" display: inline-block; background-color: GoldenRod;width: 24%;text-align: center;">GoldenRod</div>
    <div style=" display: inline-block; background-color: Lime;width: 24%;text-align: center;">Lime</div>
    <div style=" display: inline-block; background-color: MediumBlue;width: 24%; color: yellow;text-align: center;">MediumBlue</div>
    <div style=" display: inline-block; background-color: Magenta;width: 24%;text-align: center;">Magenta</div>
    <div style=" display: inline-block; background-color: Peru;width: 24%;text-align: center;">Peru</div>
    <div style=" display: inline-block; background-color: LimeGreen;width: 24%;text-align: center;">LimeGreen</div>
    <div style=" display: inline-block; background-color: MidnightBlue;width: 24%; color: yellow;text-align: center;">MidnightBlue</div>
    <div style=" display: inline-block; background-color: MediumVioletRed;width: 24%;text-align: center;">MediumVioletRed</div>
    <div style=" display: inline-block; background-color: Orange;width: 24%;text-align: center;">Orange</div>
    <div style=" display: inline-block; background-color: YellowGreen;width: 24%;text-align: center;">YellowGreen</div>
    <div style=" display: inline-block; background-color: Navy;width: 24%; color: yellow;text-align: center;">Navy</div>
    <div style=" display: inline-block; background-color: Crimson;width: 24%;text-align: center;">Crimson</div>
    <div style=" display: inline-block; background-color: DarkOrange;width: 24%;text-align: center;">DarkOrange</div>
    <div style=" display: inline-block; background-color: Olive;width: 24%;text-align: center;">Olive</div>
    <div style=" display: inline-block; background-color: DarkTurquoise;width: 24%;text-align: center;">DarkTurquoise</div>
    <div style=" display: inline-block; background-color: Violet;width: 24%;text-align: center;">Violet</div>
    <div style=" display: inline-block; background-color: Chocolate;width: 24%;text-align: center;">Chocolate</div>
    <div style=" display: inline-block; background-color: ForestGreen;width: 24%;text-align: center;">ForestGreen</div>
    <div style=" display: inline-block; background-color: DodgerBlue;width: 24%;text-align: center;">DodgerBlue</div>
    <div style=" display: inline-block; background-color: Purple;width: 24%;text-align: center;">Purple</div>
    <div style=" display: inline-block; background-color: Coral;width: 24%;text-align: center;">Coral</div>
    <div style=" display: inline-block; background-color: Chartreuse;width: 24%;text-align: center;">Chartreuse</div>
    <div style=" display: inline-block; background-color: MediumTurquoise;width: 24%;text-align: center;">MediumTurquoise</div>
    <div style=" display: inline-block; background-color: RebeccaPurple;width: 24%;text-align: center;">RebeccaPurple</div>
    <div style=" display: inline-block; background-color: BurlyWood;width: 24%;text-align: center;">BurlyWood</div>
    <div style=" display: inline-block; background-color: LawnGreen;width: 24%;text-align: center;">LawnGreen</div>
    <div style=" display: inline-block; background-color: Aqua;width: 24%;text-align: center;">Aqua</div>
    <div style=" display: inline-block; background-color: PaleVioletRed;width: 24%;text-align: center;">PaleVioletRed</div>
    <div style=" display: inline-block; background-color: OrangeRed;width: 24%;text-align: center;">OrangeRed</div>
    <div style=" display: inline-block; background-color: OliveDrab;width: 24%;text-align: center;">OliveDrab</div>
    <div style=" display: inline-block; background-color: Cyan;width: 24%;text-align: center;">Cyan</div>
    <div style=" display: inline-block; background-color: Orchid;width: 24%;text-align: center;">Orchid</div>
    <div style=" display: inline-block; background-color: SandyBrown;width: 24%;text-align: center;">SandyBrown</div>
    <div style=" display: inline-block; background-color: SpringGreen;width: 24%;text-align: center;">SpringGreen</div>
    <div style=" display: inline-block; background-color: DeepSkyBlue;width: 24%;text-align: center;">DeepSkyBlue</div>
    <div style=" display: inline-block; background-color: MediumOrchid;width: 24%;text-align: center;">MediumOrchid</div>
    <div style=" display: inline-block; background-color: DarkGoldenRod;width: 24%;text-align: center;">DarkGoldenRod</div>
    <div style=" display: inline-block; background-color: OliveDrab;width: 24%;text-align: center;">OliveDrab</div>
    <div style=" display: inline-block; background-color: DarkCyan;width: 24%;text-align: center;">DarkCyan</div>
    <div style=" display: inline-block; background-color: HotPink;width: 24%;text-align: center;">HotPink</div>
    <div style=" display: inline-block; background-color: DarkKhaki;width: 24%;text-align: center;">DarkKhaki</div>
    <div style=" display: inline-block; background-color: OliveDrab;width: 24%;text-align: center;">OliveDrab</div>
    <div style=" display: inline-block; background-color: CornflowerBlue;width: 24%;text-align: center;">CornflowerBlue</div>
    <div style=" display: inline-block; background-color: IndianRed;width: 24%;text-align: center;">IndianRed</div>
    <div style=" display: inline-block; background-color: SaddleBrown;width: 24%;text-align: center;">SaddleBrown</div>
    <div style=" display: inline-block; background-color: DarkOliveGreen;width: 24%;text-align: center;">DarkOliveGreen</div>
    <div style=" display: inline-block; background-color: LightSeaGreen;width: 24%;text-align: center;">LightSeaGreen</div>
    <div style=" display: inline-block; background-color: Fuchsia;width: 24%;text-align: center;">Fuchsia</div>
    <div style=" display: inline-block; background-color: PaleGoldenRod;width: 24%;text-align: center;">PaleGoldenRod</div>
    <div style=" display: inline-block; background-color: GreenYellow;width: 24%;text-align: center;">GreenYellow</div>
    <div style=" display: inline-block; background-color: RoyalBlue;width: 24%;text-align: center;">RoyalBlue</div>

    <div style=" display: inline-block; background-color: Indigo;width: 24%;text-align: center;">Indigo</div>
    <div style=" display: inline-block; background-color: Tan;width: 24%;text-align: center;">Tan</div>
    <div style=" display: inline-block; background-color: MediumSeaGreen;width: 24%;text-align: center;">MediumSeaGreen</div>
    <div style=" display: inline-block; background-color: Teal;width: 24%;text-align: center;">Teal</div>
    <div style=" display: inline-block; background-color: BlueViolet;width: 24%;text-align: center;">BlueViolet</div>
    <div style=" display: inline-block; background-color: Sienna;width: 24%;text-align: center;">Sienna</div>
    <div style=" display: inline-block; background-color: SeaGreen;width: 24%;text-align: center;">SeaGreen</div>
    <div style=" display: inline-block; background-color: Aquamarine;width: 24%;text-align: center;">Aquamarine</div>
    <div style=" display: inline-block; background-color: DarkOrchid;width: 24%;text-align: center;">DarkOrchid</div>
    <div style=" display: inline-block; background-color: LemonChiffon;width: 24%;text-align: center;">LemonChiffon</div>
    <div style=" display: inline-block; background-color: MediumSpringGreen;width: 24%;text-align: center;">MediumSpringGreen</div>
    <div style=" display: inline-block; background-color: LightSkyBlue;width: 24%;text-align: center;">LightSkyBlue</div>
    <div style=" display: inline-block; background-color: DarkViolet;width: 24%;text-align: center;">DarkViolet</div>
    <div style=" display: inline-block; background-color: FireBrick;width: 24%;text-align: center;">FireBrick</div>
    <div style=" display: inline-block; background-color: PaleGreen;width: 24%;text-align: center;">PaleGreen</div>
    <div style=" display: inline-block; background-color: CadetBlue;width: 24%;text-align: center;">CadetBlue</div>
    <div style=" display: inline-block; background-color: DarkMagenta;width: 24%;text-align: center;">DarkMagenta</div>
    <div style=" display: inline-block; background-color: Brown;width: 24%;text-align: center;">Brown</div>
    <div style=" display: inline-block; background-color: MediumAquaMarine;width: 24%;text-align: center;">MediumAquaMarine</div>
    <div style=" display: inline-block; background-color: SkyBlue;width: 24%;text-align: center;">SkyBlue</div>
    <div style=" display: inline-block; background-color: DeepPink;width: 24%;text-align: center;">DeepPink</div>
    <div style=" display: inline-block; background-color: Bisque;width: 24%;text-align: center;">Bisque</div>
    <div style=" display: inline-block; background-color: DarkSlateGray;width: 24%; color: yellow;text-align: center;">DarkSlateGray</div>
    <div style=" display: inline-block; background-color: Turquoise;width: 24%;text-align: center;">Turquoise</div>
    <div style=" display: inline-block; background-color: LightCoral;width: 24%;text-align: center;">LightCoral</div>
    <div style=" display: inline-block; background-color: LightGoldenRodYellow;width: 24%;text-align: center;">LightGoldenRodYellow</div>
    <div style=" display: inline-block; background-color: DarkSeaGreen;width: 24%;text-align: center;">DarkSeaGreen</div>
    <div style=" display: inline-block; background-color: Pink;width: 24%;text-align: center;">Pink</div>
    <div style=" display: inline-block; background-color: Khaki;width: 24%;text-align: center;">Khaki</div>
    <div style=" display: inline-block; background-color: DarkSlateGrey;width: 24%; color: yellow;text-align: center;">DarkSlateGrey</div>
    <div style=" display: inline-block; background-color: LightBlue;width: 24%;text-align: center;">LightBlue</div>
    <div style=" display: inline-block; background-color: Plum;width: 24%;text-align: center;">Plum</div>
    <div style=" display: inline-block; background-color: SeaShell;width: 24%;text-align: center;">SeaShell</div>
    <div style=" display: inline-block; background-color: PowderBlue;width: 24%;text-align: center;">PowderBlue</div>
    <div style=" display: inline-block; background-color: SteelBlue;width: 24%;text-align: center;">SteelBlue</div>
    <div style=" display: inline-block; background-color: Salmon;width: 24%;text-align: center;">Salmon</div>
    <div style=" display: inline-block; background-color: AliceBlue;width: 24%;text-align: center;">AliceBlue</div>
    <div style=" display: inline-block; background-color: Azure;width: 24%;text-align: center;">Azure</div>
    <div style=" display: inline-block; background-color: AntiqueWhite;width: 24%;text-align: center;">AntiqueWhite</div>
    <div style=" display: inline-block; background-color: Tomato;width: 24%;text-align: center;">Tomato</div>
    <div style=" display: inline-block; background-color: BlanchedAlmond;width: 24%;text-align: center;">BlanchedAlmond</div>
    <div style=" display: inline-block; background-color: Beige;width: 24%;text-align: center;">Beige</div>
    <div style=" display: inline-block; background-color: Cornsilk;width: 24%;text-align: center;">Cornsilk</div>
    <div style=" display: inline-block; background-color: DarkSalmon;width: 24%;text-align: center;">DarkSalmon</div>
    <div style=" display: inline-block; background-color: FloralWhite;width: 24%;text-align: center;">FloralWhite</div>
    <div style=" display: inline-block; background-color: Gainsboro;width: 24%;text-align: center;">Gainsboro</div>
    <div style=" display: inline-block; background-color: GhostWhite;width: 24%;text-align: center;">GhostWhite</div>
    <div style=" display: inline-block; background-color: HoneyDew;width: 24%;text-align: center;">HoneyDew</div>
    <div style=" display: inline-block; background-color: Lavender;width: 24%;text-align: center;">Lavender</div>
    <div style=" display: inline-block; background-color: LavenderBlush;width: 24%;text-align: center;">LavenderBlush</div>
    <div style=" display: inline-block; background-color: LightCyan;width: 24%;text-align: center;">LightCyan</div>
    <div style=" display: inline-block; background-color: LightGray;width: 24%;text-align: center;">LightGray</div>
    <div style=" display: inline-block; background-color: LightGray;width: 24%;text-align: center;">LightGrey</div>
    <div style=" display: inline-block; background-color: LightGray;width: 24%;text-align: center;">LightGreen</div>
    <div style=" display: inline-block; background-color: LightGray;width: 24%;text-align: center;">LightPink</div>
    <div style=" display: inline-block; background-color: DarkGray;width: 24%;text-align: center;">DarkGray</div>
    <div style=" display: inline-block; background-color: DarkGrey;width: 24%;text-align: center;">DarkGrey</div>
    <div style=" display: inline-block; background-color: LightSlateGray;width: 24%;text-align: center;">LightSlateGray</div>
    <div style=" display: inline-block; background-color: LightSlateGrey;width: 24%;text-align: center;">LightSlateGrey</div>
    <div style=" display: inline-block; background-color: SlateGray;width: 24%;text-align: center;">SlateGray</div>
    <div style=" display: inline-block; background-color: SlateGrey;width: 24%;text-align: center;">SlateGrey</div>
    <div style=" display: inline-block; background-color: Gray;width: 24%;text-align: center;">Gray</div>
    <div style=" display: inline-block; background-color: Grey;width: 24%;text-align: center;">Grey</div>
    <div style=" display: inline-block; background-color: DimGray;width: 24%;text-align: center;">DimGray</div>
    <div style=" display: inline-block; background-color: DimGrey;width: 24%;text-align: center;">DimGrey</div>
    <div style=" display: inline-block; background-color: LightSalmon;width: 24%;text-align: center;">LightSalmon</div>
    <div style=" display: inline-block; background-color: LightSteelBlue;width: 24%;text-align: center;">LightSteelBlue</div>
    <div style=" display: inline-block; background-color: PaleTurquoise;width: 24%;text-align: center;">PaleTurquoise</div>
    <div style=" display: inline-block; background-color: DarkSlateBlue;width: 24%; color: yellow;text-align: center;">DarkSlateBlue</div>
    <div style=" display: inline-block; background-color: MediumPurple;width: 24%;text-align: center;">MediumPurple</div>
    <div style=" display: inline-block; background-color: MediumSlateBlue;width: 24%;text-align: center;">MediumSlateBlue</div>
    <div style=" display: inline-block; background-color: SlateBlue;width: 24%; text-align: center;">SlateBlue</div>
    <div style=" display: inline-block; background-color: RosyBrown;width: 24%;text-align: center;">RosyBrown</div>
    <div style=" display: inline-block; background-color: Moccasin;width: 24%;text-align: center;">Moccasin</div>
    <div style=" display: inline-block; background-color: NavajoWhite;width: 24%;text-align: center;">NavajoWhite</div>
    <div style=" display: inline-block; background-color: Silver;width: 24%;text-align: center;">Silver</div>
    <div style=" display: inline-block; background-color: Thistle;width: 24%;text-align: center;">Thistle</div>
    <div style=" display: inline-block; background-color: PeachPuff;width: 24%;text-align: center;">PeachPuff</div>
    <div style=" display: inline-block; background-color: Wheat;width: 24%;text-align: center;">Wheat</div>
    <div style=" display: inline-block; background-color: OldLace;width: 24%;text-align: center;">OldLace</div>
    <div style=" display: inline-block; background-color: PapayaWhip;width: 24%;text-align: center;">PapayaWhip</div>
    <div style=" display: inline-block; background-color: MistyRose;width: 24%;text-align: center;">MistyRose</div>
    <div style=" display: inline-block; background-color: Snow;width: 24%;text-align: center;">Snow</div>
    <div style=" display: inline-block; background-color: Linen;width: 24%;text-align: center;">Linen</div>
    <div style=" display: inline-block; background-color: LightYellow;width: 24%;text-align: center;">LightYellow</div>
    <div style=" display: inline-block; background-color: MintCream;width: 24%;text-align: center;">MintCream</div>
    <div style=" display: inline-block; background-color: White;width: 24%;text-align: center;">White</div>
    <div style=" display: inline-block; background-color: WhiteSmoke;width: 24%;text-align: center;">WhiteSmoke</div>
    <div style=" display: inline-block; background-color: Ivory;width: 24%;text-align: center;">Ivory</div>
    <div style=" display: inline-block; background-color: Black;width: 24%;color: yellow; text-align: center;">Black</div>
  </div>
  `
);